spring:
  application:
    name: tichu-sim
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 600    # 10 mins
    refreshTokenExpiration: 7200  # 2 hrs
    webSocketTokenExpiration: 60  # 1 min
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN}
  rooms:
    id-length: 5
