export enum TichuMessageType {
  SET_RULE = 'SET_RULE',
  START = 'START',
  INIT_FIRST_DRAWS = 'INIT_FIRST_DRAWS',
  LARGE_TICHU = 'LARGE_TICHU',
  ADD_SECOND_DRAWS = 'ADD_SECOND_DRAWS',
  SMALL_TICHU = 'SMALL_TICHU',
  EXCHANGE = 'EXCHANGE',
  PHASE_START = 'PHASE_START',
  PLAY_TRICK = 'PLAY_TRICK',
  PLAY_BOMB = 'PLAY_BOMB',
  PASS = 'PASS',
  PHASE_END_WITH_DRAGON = 'PHASE_END_WITH_DRAGON',
  SELECT_DRAGON_RECEIVER = 'SELECT_DRAGON_RECEIVER',
  ROUND_END = 'ROUND_END',
  END = 'END',
  GET = 'GET',
}

export interface TichuMessage {
  type: TichuMessageType;
  data: unknown;
}
