name: CD - Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  check:
    uses: ./.github/workflows/reusable-check.yaml

  publish:
    needs: check
    uses: ./.github/workflows/reusable-docker.yaml
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  deploy:
    needs: publish
    uses: ./.github/workflows/reusable-deploy.yaml
    secrets:
      SSH_HOST: ${{ secrets.LIGHTSAIL_SSH_HOST }}
      SSH_USER: ${{ secrets.LIGHTSAIL_SSH_USER }}
      SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}
